# Generated by Django 4.2.1 on 2024-11-08 10:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_teacher_current_amount_4_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_direction', models.CharField(db_index=True, max_length=100, verbose_name='Название направления')),
                ('direction_code', models.CharField(db_index=True, max_length=100, verbose_name='Код направления')),
                ('group_number', models.CharField(db_index=True, max_length=100, verbose_name='Номер группы')),
            ],
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='current_amount_3_course',
            new_name='current_amount_3_course_01_03_02',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='current_amount_4_course',
            new_name='current_amount_3_course_02_03_02',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='current_amount_m',
            new_name='current_amount_3_course_02_03_03',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='max_amount_3_course',
            new_name='max_amount_3_course_01_03_02',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='max_amount_4_course',
            new_name='max_amount_3_course_02_03_02',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='max_amount_m',
            new_name='max_amount_3_course_02_03_03',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='teacher',
            name='current_amount_3_course_09_03_03',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='current_amount_m_01_04_02',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='current_amount_m_02_04_02',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='current_amount_m_09_04_02',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='max_amount_3_course_09_03_03',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='max_amount_m_01_04_02',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='max_amount_m_02_04_02',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='max_amount_m_09_04_02',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='student',
            name='direction_of_study',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st', to='users.directionofstudy', verbose_name='Направление обучения'),
        ),
    ]
