# Generated by Django 4.2.1 on 2024-11-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_directionofstudy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='direction_of_study',
        ),
        migrations.DeleteModel(
            name='DirectionOfStudy',
        ),
    ]
