# Generated by Django 4.2.1 on 2024-11-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_student_direction_of_study_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_direction', models.CharField(db_index=True, max_length=100, verbose_name='Название направления')),
                ('direction_code', models.CharField(db_index=True, max_length=100, verbose_name='Код направления')),
                ('group_number', models.CharField(db_index=True, max_length=100, verbose_name='Номер группы')),
            ],
        ),
    ]
