# Generated by Django 4.2.1 on 2024-11-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_directionofstudy_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_direction', models.CharField(db_index=True, max_length=100, verbose_name='Название направления')),
                ('direction_code', models.CharField(db_index=True, max_length=100, verbose_name='Код направления')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='direction_code',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name_of_direction',
        ),
        migrations.AddField(
            model_name='group',
            name='direction_of_study',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gr', to='users.directionofstudy', verbose_name='Направление обучения'),
        ),
    ]
