# Generated by Django 4.2.1 on 2024-11-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_directionofstudy_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scientific_director',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st', to='users.teacher'),
        ),
    ]
