# Generated by Django 4.2.1 on 2024-11-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_teacher_current_amount_3_course_01_03_02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionofstudy',
            name='direction_code',
            field=models.CharField(max_length=100, verbose_name='Код направления'),
        ),
        migrations.AlterField(
            model_name='directionofstudy',
            name='level_of_training',
            field=models.CharField(blank=True, choices=[('BD', 'Бакалавриат'), ('MD', 'Магистратура')], default='BD', max_length=100, verbose_name='Уровень подготовки'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'Кафедра информационных технологий'), ('CT', 'Кафедра вычислительных технологий'), ('MM', 'Кафедра математического моделирования'), ('DAAAI', 'Кафедра анализа данных и искусственного интеллекта'), ('AM', 'Кафедра прикладной математики')], default='IT', max_length=100, verbose_name='Кафедра'),
        ),
    ]
