# Generated by Django 4.2.1 on 2024-11-16 10:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_teacher_current_amount_3_course_01_03_02_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationAboutTheNumberOfSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество')),
                ('max_amount', models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество')),
                ('direction_of_study', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages4', to='users.directionofstudy', verbose_name='Направление обучения')),
                ('teacher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages1', to='users.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Информация о количестве мест',
                'verbose_name_plural': 'Информация о количестве мест',
            },
        ),
    ]
