# Generated by Django 4.2.1 on 2024-10-19 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Кафедра')),
                ('current_amount_3_course', models.IntegerField(blank=True, default=0)),
                ('max_amount_3_course', models.IntegerField(blank=True, default=5)),
                ('current_amount_4_course', models.IntegerField(blank=True, default=0)),
                ('max_amount_4_course', models.IntegerField(blank=True, default=5)),
                ('current_amount_m', models.IntegerField(blank=True, default=0)),
                ('max_amount_m', models.IntegerField(blank=True, default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(blank=True, default=3, verbose_name='Курс')),
                ('group', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Группа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
