# Generated by Django 4.2.1 on 2024-11-08 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_directionofstudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='direction_of_study',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st', to='users.directionofstudy', verbose_name='Направление обучения'),
        ),
    ]
