# Generated by Django 4.2.1 on 2024-11-09 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_student_direction_of_study'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirectionOfStudy',
            new_name='Group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='direction_of_study',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st', to='users.group', verbose_name='Группа'),
        ),
    ]
