# Generated by Django 4.2.1 on 2024-11-09 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_directionofstudy_remove_group_direction_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionofstudy',
            options={'verbose_name': 'Направление обучения', 'verbose_name_plural': 'Направления обучения'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AddField(
            model_name='directionofstudy',
            name='level_of_training',
            field=models.CharField(blank=True, choices=[('BD', 'Бакалавриат'), ('MD', 'Магистратура')], db_index=True, default='BD', max_length=100, verbose_name='Уровень подготовки'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_3_course_01_03_02',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 01.03.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_3_course_02_03_02',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 02.03.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_3_course_02_03_03',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 02.03.03'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_3_course_09_03_03',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 09.03.03'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_m_01_04_02',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 01.04.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_m_02_04_02',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 02.04.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_m_09_04_02',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 09.04.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_3_course_01_03_02',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 01.03.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_3_course_02_03_02',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 02.03.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_3_course_02_03_03',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 02.03.03'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_3_course_09_03_03',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 09.03.03'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_m_01_04_02',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 01.04.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_m_02_04_02',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 02.04.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_m_09_04_02',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 09.04.02'),
        ),
    ]
