# Generated by Django 4.2.1 on 2024-11-15 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_student_scientific_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_3_course_01_03_02',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 01.03.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_3_course_02_03_02',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 02.03.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_3_course_02_03_03',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 02.03.03'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_3_course_09_03_03',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 09.03.03'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_m_01_04_02',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 01.04.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_m_02_04_02',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 02.04.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_amount_m_09_04_02',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество 09.04.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_3_course_01_03_02',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 01.03.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_3_course_02_03_02',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 02.03.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_3_course_02_03_03',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 02.03.03'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_3_course_09_03_03',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 09.03.03'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_m_01_04_02',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 01.04.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_m_02_04_02',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 02.04.02'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_amount_m_09_04_02',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Максимальное количество 09.04.02'),
        ),
    ]
