# Generated by Django 4.2.1 on 2024-11-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_directionofstudy_direction_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='current_amount_3_course_01_03_02',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='current_amount_3_course_02_03_02',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='current_amount_3_course_02_03_03',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='current_amount_3_course_09_03_03',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='current_amount_m_01_04_02',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='current_amount_m_02_04_02',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='current_amount_m_09_04_02',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='max_amount_3_course_01_03_02',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='max_amount_3_course_02_03_02',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='max_amount_3_course_02_03_03',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='max_amount_3_course_09_03_03',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='max_amount_m_01_04_02',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='max_amount_m_02_04_02',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='max_amount_m_09_04_02',
        ),
    ]
