# Generated by Django 4.2.1 on 2024-11-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_informationaboutthenumberofseats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationaboutthenumberofseats',
            name='direction_of_study',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='direction', to='users.directionofstudy', verbose_name='Направление обучения'),
        ),
        migrations.AlterField(
            model_name='informationaboutthenumberofseats',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='users.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='student',
            name='scientific_director',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st', to='users.teacher', verbose_name='Научный руководитель'),
        ),
        migrations.AddConstraint(
            model_name='informationaboutthenumberofseats',
            constraint=models.UniqueConstraint(fields=('teacher', 'direction_of_study'), name='some_unique_name'),
        ),
    ]
