# Generated by Django 6.0.1 on 2026-04-17 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_informationaboutthenumberofseats_direction_of_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Для бакалавриата: 3 или 4. Для магистратуры не заполняется.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Курс'),
        ),
    ]
