# Generated by Django 6.0.1 on 2026-04-18 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_teacher_course_seats(apps, schema_editor):
    Teacher = apps.get_model("users", "Teacher")
    TeacherCourseSeat = apps.get_model("users", "TeacherCourseSeat")
    Student = apps.get_model("users", "Student")
    buckets = ("b3", "b4", "m1", "m2")
    for t in Teacher.objects.all():
        for b in buckets:
            TeacherCourseSeat.objects.get_or_create(
                teacher=t, bucket=b, defaults={"current_amount": 0, "max_amount": 5}
            )
    counts = {}
    for st in Student.objects.filter(scientific_director__isnull=False).select_related(
        "group__direction_of_study"
    ):
        c = getattr(getattr(st, "group", None), "course", None)
        if c is None:
            continue
        buck = None
        g = st.group
        if g and g.direction_of_study_id:
            lv = g.direction_of_study.level_of_training
            if lv == "BD":
                if c == 3:
                    buck = "b3"
                elif c == 4:
                    buck = "b4"
            elif lv == "MD":
                if c == 1:
                    buck = "m1"
                elif c == 2:
                    buck = "m2"
        if buck is None:
            if c == 3:
                buck = "b3"
            elif c == 4:
                buck = "b4"
            elif c == 1:
                buck = "m1"
            elif c == 2:
                buck = "m2"
        if buck:
            tid = st.scientific_director_id
            counts[(tid, buck)] = counts.get((tid, buck), 0) + 1
    for (tid, buck), n in counts.items():
        TeacherCourseSeat.objects.filter(teacher_id=tid, bucket=buck).update(current_amount=n)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_diploma_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Бакалавриат: 3 или 4; магистратура: 1 или 2.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Курс'),
        ),
        migrations.CreateModel(
            name='TeacherCourseSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(choices=[('b3', 'Бакалавриат, 3 курс'), ('b4', 'Бакалавриат, 4 курс'), ('m1', 'Магистратура, 1 курс'), ('m2', 'Магистратура, 2 курс')], db_index=True, max_length=2)),
                ('current_amount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Занято')),
                ('max_amount', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Лимит')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_seats', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Лимит по курсу',
                'verbose_name_plural': 'Лимиты по курсам',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'bucket'), name='uniq_teacher_course_bucket')],
            },
        ),
        migrations.RunPython(seed_teacher_course_seats, migrations.RunPython.noop),
    ]
