# Generated by Django 4.2.1 on 2024-11-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_work_author_alter_work_scientific_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='year',
        ),
    ]
