# Generated by Django 4.2.1 on 2024-11-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_work_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='work',
            name='type_of_work',
            field=models.CharField(max_length=100, verbose_name='Тип работы'),
        ),
    ]
