# Generated by Django 6.0.1 on 2026-04-16 01:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_informationaboutthenumberofseats_direction_of_study_and_more'),
        ('works', '0005_alter_work_description_alter_work_type_of_work'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.RemoveField(
            model_name='work',
            name='file_word',
        ),
        migrations.RemoveField(
            model_name='work',
            name='year',
        ),
        migrations.AddField(
            model_name='work',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено'),
        ),
        migrations.AddField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'На проверке'), ('needs_changes', 'Требует доработки'), ('approved', 'Готово'), ('archived', 'В архиве')], db_index=True, default='draft', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='work',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='users.student', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='work',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='work',
            name='scientific_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='users.teacher', verbose_name='Научный руководитель'),
        ),
        migrations.AlterField(
            model_name='work',
            name='type_of_work',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Тип работы'),
        ),
        migrations.CreateModel(
            name='IndividualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='works.work')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlanStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_done', models.BooleanField(db_index=True, default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='works.individualplan')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Название темы')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='users.teacher', verbose_name='Автор (преподаватель)')),
            ],
            options={
                'verbose_name': 'Тема (банк)',
                'verbose_name_plural': 'Темы (банк)',
            },
        ),
        migrations.CreateModel(
            name='WorkVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.CharField(blank=True, default='', max_length=300)),
                ('file', models.FileField(upload_to='work_versions/')),
                ('is_final', models.BooleanField(db_index=True, default=False)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='works.work')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='reviews/')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='works.workversion')),
            ],
        ),
        migrations.CreateModel(
            name='TopicApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Утверждена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True, default='')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_applications', to='users.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='works.topic')),
            ],
            options={
                'verbose_name': 'Заявка на тему',
                'verbose_name_plural': 'Заявки на темы',
                'constraints': [models.UniqueConstraint(fields=('student', 'topic'), name='uniq_student_topic_application')],
            },
        ),
    ]
