# Generated by Django 6.0.1 on 2026-04-16 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_alter_work_options_remove_work_file_word_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('anchor', models.CharField(blank=True, default='', max_length=200)),
                ('text', models.TextField()),
                ('student_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='works.work')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('teacher_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('student_viewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_doc_updates', to=settings.AUTH_USER_MODEL)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='works.work')),
            ],
        ),
    ]
