# Generated by Django 6.0.1 on 2026-04-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_workcomment_workdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='planstage',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='planstage',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planstage',
            name='student_ready',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
