# Generated by Django 6.0.1 on 2026-04-17 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_diploma_features'),
        ('works', '0008_planstage_overdue_notified_at_planstage_ready_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='work_kind',
            field=models.CharField(choices=[('coursework', 'Курсовая работа'), ('bachelor', 'ВКР (бакалавриат)'), ('master', 'Магистерская диссертация')], db_index=True, default='bachelor', max_length=32, verbose_name='Тип работы'),
        ),
        migrations.CreateModel(
            name='StudentTopicProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание работы')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Утверждена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True, default='')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_decisions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_proposals', to='users.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_proposals', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Предложение темы студентом',
                'verbose_name_plural': 'Предложения тем студентами',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='works', to='works.tag', verbose_name='Теги'),
        ),
    ]
