# Generated by Django 6.0.1 on 2026-04-18 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_diploma_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='planstage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='works.planstage'),
        ),
        migrations.AddField(
            model_name='work',
            name='student_docx_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Напоминание студенту о неактивности DOCX'),
        ),
        migrations.AddField(
            model_name='work',
            name='teacher_stale_docx_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Уведомление руководителю о месяце без правок'),
        ),
    ]
