# Generated by Django 4.2.1 on 2024-10-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'Кафедра информационных технологий'), ('CT', 'Кафедра вычислительных технологий'), ('MM', 'Кафедра математического моделирования'), ('DAAAI', 'Кафедра анализа данных и искусственного интеллекта'), ('AM', 'Кафедра прикладной математики')], db_index=True, default='IT', max_length=100, verbose_name='Кафедра'),
        ),
    ]
