from django.urls import path
from . import views
from topics import views as topic_views

urlpatterns = [
    path('', views.SearchWorksView.as_view(), name='home'),
    path('list_teacher/', views.ShowTeachersView.as_view(), name='list_teacher'),
    path('add_student/', views.ShowStudentsView.as_view(), name='add_student'),
    path('check_works/', views.check_works, name='check_works'),
    path('review_work/<int:work_id>/', views.teacher_review_work, name='teacher_review_work'),
    path('review_work/<int:work_id>/ready/', views.mark_work_ready, name='mark_work_ready'),
    path('review_work/<int:work_id>/norm_ok/', views.mark_work_norm_ok, name='mark_work_norm_ok'),
    path('review_work/<int:work_id>/defended/', views.mark_work_defended, name='mark_work_defended'),
    path('review_work/<int:work_id>/plan/save/', views.save_plan_stages, name='save_plan_stages'),
    path('plan/stage/<int:stage_id>/edit/', views.edit_plan_stage, name='edit_plan_stage'),
    path('plan/stage/<int:stage_id>/delete/', views.delete_plan_stage, name='delete_plan_stage'),
    path('write_work/', views.write_work, name='write_work'),
    path('stats/', views.department_stats, name='department_stats'),
    path('assign_topic/<int:student_id>/', views.assign_topic, name='assign_topic'),
    path('topics/', topic_views.topic_bank, name='topic_bank'),
    path('topics/propose/', topic_views.propose_topic, name='propose_topic'),
    path('topics/new/', topic_views.create_topic, name='create_topic'),
    path('topics/apply/<int:topic_id>/', topic_views.apply_topic, name='apply_topic'),
    path('topics/applications/', topic_views.topic_applications, name='topic_applications'),
    path('topics/applications/<int:application_id>/', topic_views.decide_topic_application, name='decide_topic_application'),
    path('topics/proposals/<int:proposal_id>/decide/', topic_views.decide_topic_proposal, name='decide_topic_proposal'),
    path('work/<int:work_id>/', views.work_detail, name='work_detail'),
    path('work/<int:work_id>/docx/editor/', views.onlyoffice_editor, name='onlyoffice_editor'),
    path('work/<int:work_id>/docx/file/', views.onlyoffice_docx_file, name='onlyoffice_docx_file'),
    path('onlyoffice/callback/<int:work_id>/', views.onlyoffice_callback, name='onlyoffice_callback'),
    path('work/<int:work_id>/edit_topic/', views.edit_work_topic, name='edit_work_topic'),
    path('work/<int:work_id>/upload/', views.upload_version, name='upload_version'),
    path('work/<int:work_id>/plan/', views.plan_detail, name='plan_detail'),
    path('work/<int:work_id>/plan/add_stage/', views.add_plan_stage, name='add_plan_stage'),
    path('plan/stage/<int:stage_id>/ready/', views.mark_stage_ready, name='mark_stage_ready'),
    path('plan/stage/<int:stage_id>/approve/', views.approve_stage, name='approve_stage'),
    path('department/teachers/', views.department_teachers_list, name='department_teachers'),
    path('department/teachers/<int:teacher_id>/', views.department_teacher_detail, name='department_teacher_detail'),
    path('department/announcement/', views.department_send_announcement, name='department_send_announcement'),
    path('notifications/', views.notifications, name='notifications'),
]
