# Generated by Django 4.2.1 on 2024-10-19 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='Описание')),
                ('type_of_work', models.CharField(db_index=True, max_length=100, verbose_name='Тип работы')),
                ('year', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('file_word', models.FileField(upload_to='uploads_model')),
                ('is_completed', models.BooleanField(verbose_name='Статус')),
                ('author', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('scientific_director', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sd', to=settings.AUTH_USER_MODEL, verbose_name='Научный руководитель')),
            ],
        ),
    ]
