# Generated by Django 4.2.1 on 2024-11-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_student_scientific_director'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='author',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st', to='users.student', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='work',
            name='scientific_director',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sd', to='users.teacher', verbose_name='Научный руководитель'),
        ),
    ]
