# Generated by Django 4.2.1 on 2024-11-15 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_remove_work_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='year',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
